version: '3.8'
services:
  vote:
    image: vote
    build:
      context: ./vote
      dockerfile: Dockerfile

  result:
    image: result
    build:
      context: ./result
      dockerfile: Dockerfile

  seed-data:
    image: seed-data
    build:
      context: ./seed-data
      dockerfile: Dockerfile

  worker:
    image: worker
    build:
      context: ./worker
      dockerfile: Dockerfile

